export const actionTypes = {
  ADD_TO_HISTORY: "ADD_TO_HISTORY",
  CLEAR_HISTORY: "CLEAR_HISTORY",
  ADD_TO_WATCHLATER: "ADD_TO_WATCHLATER",
  REMOVE_FROM_WATCHLATER: "REMOVE_FROM_WATCHLATER",
  ADD_TO_LIKED: "ADD_TO_LIKED",
  REMOVE_FROM_LIKED: "REMOVE_FROM_LIKED",
  TOGGLE_DISLIKED: "TOGGLE_DISLIKED",
  SEARCH_VIDEOS: "SEARCH_VIDEOS",
  NO_VIDEOS_FOUND: "NO_VIDEOS_FOUND"
};
